### PR TITLE
feat: Add supported network logos

### LINKED ISSUE #1: Add section for supported networks to the website
## Overview

Currently we only mention the supported networks in a small and hardly visible section. 

Screenshot 2021-12-03 at 13 49 23

## Goals

Prominently highlight the supported networks on the website

## Requirements

- [ ] design specification 
- [ ] logos 
- [ ] Load supported networks from gateway

## Screens

rough draft tbd with @liliiaorlenko 

Networks safe drawio

 - Figma: https://www.figma.com/file/F6xayQPByTA0y6pFzfzuTE/Main-Page?node-id=1%3A77
 - Zeplin:

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves
Resolves #1 

## How to test
1. Open the landing page
2. Find "Gnosis Safe Supports" section with network logos in the Overview page

## Screenshots
Screenshot 2022-05-09 at 20 20 26
Screenshot 2022-05-09 at 20 20 20
Screenshot 2022-05-09 at 20 20 08

### CODE REVIEW

**Comment by germartinez** [comment]
Please, do not squash and merge, but rebase and merge instead

**Review by iamacook — APPROVED** [review]
Following on from what @germartinez said, it would likely help to remove the space around the Aurora/Gnosis Chain logos as well.

**Comment by katspaugh** [comment]
> Please, do not squash and merge, but rebase and merge instead

No, for regular PRs you _should_ squash.

**Comment by JagoFigueroa** [comment]
Hola señores, alignment seems a bit off on mobile & with narrow resolutions in general:
IMG_0566

Screenshot 2022-05-11 at 13 14 23


Should we maybe do some center alignment for this cases?

Also, it expected to not include test nets on this list, right?

Gracias :)

**Comment by usame-algan** [comment]
> Hola señores, alignment seems a bit off on mobile & with narrow resolutions in general.
> Should we maybe do some center alignment for this cases?
> 
> Also, it expected to not include test nets on this list, right?
> 
> Gracias :)

Hey Jago, thanks for testing! I removed the whitespace in some of the logos so that they are center-aligned now.

**Comment by JagoFigueroa** [comment]
Thank you Usame! Unfortunately going smaller than 960px horizontally the center-alignment is still going a bit off for me:
Screenshot 2022-05-11 at 13 56 40

If we could match the icons vertically with the ones present in this section here I think it would be perfect:

Screenshot 2022-05-11 at 13 57 24

& on mobile (I have an iphone 13 pro) now it looks like this for me:
IMG_0567

A bit of a tricky one

**Comment by JagoFigueroa** [comment]
Looking hella fine now, thank you @usame-algan :pepe-king:

**Pull request merged**
